//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            this.bill_detail = new HashSet<bill_detail>();
            this.menu_detail = new HashSet<menu_detail>();
        }
    
        public int id { get; set; }
        public int id_type { get; set; }
        public string name { get; set; }
        public string summary { get; set; }
        public string detail { get; set; }
        public double price { get; set; }
        public double promotion_price { get; set; }
        public string promotion { get; set; }
        public string image { get; set; }
        public System.DateTime update_at { get; set; }
        public string unit { get; set; }
        public int today { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail> bill_detail { get; set; }
        public virtual food_type food_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu_detail> menu_detail { get; set; }
    }
}
